export const FETCH_QUESTIONS_START = "FETCH_QUESTIONS_START";
export const FETCH_QUESTIONS_SUCCESS = "FETCH_QUESTIONS_SUCCESS";

export const UPDATE_USERNAME = "UPDATE_USERNAME";
export const UPDATE_USER_ANSWER = "UPDATE_USER_ANSWER";
